# Generated by Django 3.0.7 on 2020-06-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=14)),
                ('city', models.CharField(max_length=150)),
                ('aprovado', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(to='products.Products')),
            ],
        ),
    ]
